variables:
  COMPOSER_CACHE_DIR: '/cache/composer'
  COMPOSER_ALLOW_SUPERUSER: '1'
  COMPOSER_NO_INTERACTION: '1'

stages:
  - build
  - test

build:test:
  stage: build
  image: webdevops/php:7.4
  before_script:
    - composer self-update
    - composer global require hirak/prestissimo --no-progress
  script:
    - composer install --no-progress
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_NAME"
    paths:
      - vendor/
    expire_in: 1h

.test: &test-template
  stage: test
  image: webdevops/php-dev:$DOCKER_TAG
  dependencies:
    - build:test
  script:
    - composer test -- --coverage-text --colors=never --testdox
  coverage: '/^\s*Lines:\s*\d+.\d+\%/'
  only:
    - branches

test:7.3:
  <<: *test-template
  variables:
    DOCKER_TAG: '7.3'

test:7.4:
  <<: *test-template
  variables:
    DOCKER_TAG: '7.4'
