name: Pull Request

inputs:
  run-id:
    required: true
    type: string
  token:
    required: true

runs:
  using: 'composite'
  steps:
    - uses: actions/github-script@v8
      env:
        RUN_ID: ${{ inputs.run-id }}
      with:
        github-token: ${{ inputs.token }}
        script: |
          github.rest.actions.cancelWorkflowRun({
            owner: context.repo.owner,
            repo: context.repo.repo,
            run_id: process.env.RUN_ID,
          })
          .then(() => {
            function checkRunStatus() {
              return github.rest.actions.getWorkflowRun({
                owner: context.repo.owner,
                repo: context.repo.repo,
                run_id: process.env.RUN_ID,
              })
              .then(run => {
                console.log(run.data.status);
                if (run.data.status !== 'completed') {
                  return checkRunStatus();
                }
              });
            }

            return checkRunStatus();
          })
          .then(() => github.rest.actions.deleteWorkflowRun({
            owner: context.repo.owner,
            repo: context.repo.repo,
            run_id: process.env.RUN_ID,
          }));
