name: CGL
on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main

jobs:
  prepare:
    name: Prepare workflow
    runs-on: ubuntu-latest
    outputs:
      continue: ${{ steps.continue.outputs.continue }}
    steps:
      - id: continue
        uses: actions/github-script@v7
        with:
          script: |
            if (context.eventName === 'pull_request') {
              core.setOutput('continue', context.payload.pull_request.head.repo.owner !== 'eliashaeussler');
            } else {
              core.setOutput('continue', true);
            }

  cgl:
    runs-on: ubuntu-latest
    needs: prepare
    if: needs.prepare.outputs.continue
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Prepare environment
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          # @todo Use PHP 8.4 once PHP-CS-Fixer supports PHP 8.4
          php-version: 8.3
          tools: composer:v2, composer-require-checker, composer-unused, cs2pr
          coverage: none

      # Validation
      - name: Validate composer.json
        run: composer validate --no-check-lock

      # Install dependencies
      - name: Install Composer dependencies
        run: composer require --no-progress spomky-labs/otphp:"^11.0"

      # Check Composer dependencies
      - name: Check dependencies
        run: composer-require-checker check
      - name: Reset composer.json
        run: |
          git checkout composer.*
          composer install --no-progress
      - name: Check for unused dependencies
        run: composer-unused

      # Linting
      - name: Lint composer.json
        run: composer lint:composer
      - name: Lint Editorconfig
        run: composer lint:editorconfig
      - name: Lint PHP
        run: composer lint:php -- --format=checkstyle | cs2pr

      # SCA
      - name: SCA PHP
        run: composer sca:php -- --error-format github

      # Migration
      - name: Run Rector migration
        run: composer migration:rector -- --dry-run
